gemini_2_provider.settings:
  type: mapping
  label: 'Gemini 2 Provider Settings'
  mapping:
    api_key:
      type: string
      label: 'The API key for Gemini API.'
    model_id:
        type: string
        label: 'The Gemini Model ID'
        default: 'gemini-2.0-flash-exp'
